TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
NAME: ptr_int_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- TYPE: SIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
NAME: ptr_int_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- TYPE: SIGNED INT
NAME: ptr_int_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- POINTER TO
-- -- -- -- TYPE: SIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
NAME: ptr_int_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- TYPE: SIGNED INT
NAME: ptr_int_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- POINTER TO
-- -- -- -- TYPE: SIGNED INT
NAME: unsigned_char_fn_
ROLE: SYM_FUNC
SCOPE: SYM_GLOBAL
RETURN TYPE: 
-- UNOP: FUNCTION THAT RETURNS TYPE
-- -- TYPE: UNSIGNED CHAR
CONTENT: 
-- COMPOUND:
-- -- BLOCK:
-- -- -- RETURN:
-- -- -- -- CHAR: 'x'
FUNCTION DEFINITION:
-- UNOP: FUNCTION THAT RETURNS TYPE
-- -- TYPE: UNSIGNED CHAR
-- COMPOUND:
-- -- BLOCK:
-- -- -- RETURN:
-- -- -- -- CHAR: 'x'
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
NAME: ptr_int_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- TYPE: SIGNED INT
NAME: ptr_int_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- POINTER TO
-- -- -- -- TYPE: SIGNED INT
NAME: unsigned_char_fn_
ROLE: SYM_FUNC
SCOPE: SYM_GLOBAL
RETURN TYPE: 
-- UNOP: FUNCTION THAT RETURNS TYPE
-- -- TYPE: UNSIGNED CHAR
CONTENT: 
-- COMPOUND:
-- -- BLOCK:
-- -- -- RETURN:
-- -- -- -- CHAR: 'x'
NAME: long_long_long_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
NAME: ptr_int_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- TYPE: SIGNED INT
NAME: ptr_int_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- POINTER TO
-- -- -- -- TYPE: SIGNED INT
NAME: unsigned_char_fn_
ROLE: SYM_FUNC
SCOPE: SYM_GLOBAL
RETURN TYPE: 
-- UNOP: FUNCTION THAT RETURNS TYPE
-- -- TYPE: UNSIGNED CHAR
CONTENT: 
-- COMPOUND:
-- -- BLOCK:
-- -- -- RETURN:
-- -- -- -- CHAR: 'x'
NAME: long_long_long_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: a
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
TABLE SCOPE: TABLE_GLOBAL
NAME: int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: long_long_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: long_long_unsigned_int_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED LONG LONG
NAME: unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: signed_char_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED CHAR
NAME: signed_short_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED SHORT
NAME: extern_unsigned_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: UNSIGNED INT
NAME: extern_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_EXPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: void_ptr_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- TYPE: VOID
NAME: void_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- POINTER TO
-- -- -- TYPE: VOID
NAME: ptr_int_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- TYPE: SIGNED INT
NAME: ptr_int_ptr_ary_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- POINTER TO
-- -- ARRAY OF UNSPECIFIED SIZE OF TYPE
-- -- -- POINTER TO
-- -- -- -- TYPE: SIGNED INT
NAME: unsigned_char_fn_
ROLE: SYM_FUNC
SCOPE: SYM_GLOBAL
RETURN TYPE: 
-- UNOP: FUNCTION THAT RETURNS TYPE
-- -- TYPE: UNSIGNED CHAR
CONTENT: 
-- COMPOUND:
-- -- BLOCK:
-- -- -- RETURN:
-- -- -- -- CHAR: 'x'
NAME: long_long_long_
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED LONG LONG
NAME: a
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
NAME: i
ROLE: SYM_VAR
SCOPE: SYM_GLOBAL
STORAGE CLASS: CLASS_EXTERN_IMPLICIT
DEFINED
TYPE: 
-- TYPE: SIGNED INT
BINOP: =
-- IDENT: i
-- NUMLIT: 0
BINOP: =
-- IDENT: a
-- NUMLIT: 4
FOR:
-- UNOP: i++
-- -- IDENT: i
-- UNOP: i++
-- -- IDENT: i
-- COMPOUND:
-- -- BLOCK:
-- -- -- UNOP: i++
-- -- -- -- IDENT: a
BINOP: =
-- IDENT: a
-- NUMLIT: 0
