
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[408] =
    {   0,
      110,  108,  109,  107,  108,  109,   86,  107,  109,   15,
      108,  109,  100,  108,  109,  108,  109,   13,  108,  109,
        6,  108,  109,   94,  108,  109,    8,  108,  109,    9,
      108,  109,   24,  108,  109,    2,  108,  109,   20,  108,
      109,    3,    5,  108,  109,   17,   21,  108,  109,   12,
      108,  109,   92,  108,  109,   88,   92,  108,  109,   22,
      108,  109,    1,  108,  109,   19,  108,  109,    4,  108,
      109,   18,  108,  109,   23,  108,  109,  106,  108,  109,
       10,  108,  109,   11,  108,  109,   14,  108,  109,  106,
      108,  109,  106,  108,  109,  106,  108,  109,  106,  108,

      109,  106,  108,  109,  106,  108,  109,  106,  108,  109,
      106,  108,  109,  106,  108,  109,  106,  108,  109,  106,
      108,  109,  106,  108,  109,  106,  108,  109,  106,  108,
      109,  106,  108,  109,  106,  108,  109,   25,  108,  109,
        7,  108,  109,   26,  108,  109,   16,  108,  109,   99,
      109,  109,   99,  109,   99,  109,  104,  109,  105,  109,
      109,  107,   35,   41,   36,   46,   39,   28,   42,   29,
       43,   27,   92,   40,   92,   91,   92,   92,   92,   88,
       92,   30,   32,   34,   33,   31,  106,   48,  106,  106,
      106,  106,  106,  106,  106,  106,  106,   56,  106,  106,

      106,  106,  106,  106,  106,   64,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,   47,   37,
       98,   98,  103,  103,   38,   92,   89,   92,   90,   93,
       44,   45,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,   62,  106,  106,  106,
       66,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,   95,   93,
       93,   93,  106,  106,  106,   49,  106,  106,   51,  106,
       52,  106,  106,  106,  106,  106,   58,  106,   59,  106,
      106,  106,   63,  106,  106,   67,  106,  106,  106,  106,

      106,  106,  106,  106,  106,  106,  106,  106,  106,   80,
      106,  106,  106,  102,  101,   93,   93,   83,  106,  106,
      106,   50,  106,   53,  106,  106,  106,  106,  106,   61,
      106,  106,  106,  106,  106,   71,  106,  106,  106,  106,
      106,  106,  106,   78,  106,  106,  106,   82,  106,   97,
       96,   87,   87,  106,  106,  106,  106,   57,  106,   60,
      106,   65,  106,  106,  106,   70,  106,   72,  106,   73,
      106,   74,  106,   75,  106,   76,  106,  106,  106,  106,
      106,  106,  106,   55,  106,  106,  106,   77,  106,  106,
      106,   84,  106,  106,   54,  106,   68,  106,   69,  106,

       79,  106,   81,  106,  106,   85,  106
    } ;

static const flex_int16_t yy_accept[297] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
       10,   13,   16,   18,   21,   24,   27,   30,   33,   36,
       39,   42,   46,   50,   53,   56,   60,   63,   66,   69,
       72,   75,   78,   81,   84,   87,   90,   93,   96,   99,
      102,  105,  108,  111,  114,  117,  120,  123,  126,  129,
      132,  135,  138,  141,  144,  147,  150,  152,  153,  155,
      157,  159,  161,  162,  163,  164,  164,  164,  165,  166,
      167,  168,  169,  170,  171,  172,  173,  173,  174,  175,
      176,  178,  179,  179,  179,  180,  180,  182,  183,  184,
      185,  186,  187,  188,  189,  190,  191,  192,  193,  194,

      195,  196,  197,  198,  200,  201,  202,  203,  204,  205,
      206,  208,  209,  210,  211,  212,  213,  214,  215,  216,
      217,  218,  219,  220,  221,  222,  222,  223,  223,  223,
      224,  225,  225,  225,  225,  225,  226,  227,  228,  228,
      229,  229,  231,  232,  233,  234,  235,  236,  237,  238,
      239,  240,  241,  242,  243,  244,  245,  246,  247,  249,
      250,  251,  253,  254,  255,  256,  257,  258,  259,  260,
      261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
      270,  270,  270,  270,  270,  271,  272,  273,  273,  274,
      275,  276,  278,  279,  281,  283,  284,  285,  286,  287,

      289,  291,  292,  293,  295,  296,  298,  299,  300,  301,
      302,  303,  304,  305,  306,  307,  308,  309,  310,  312,
      313,  314,  314,  314,  315,  316,  316,  317,  317,  318,
      320,  321,  322,  324,  326,  327,  328,  329,  330,  332,
      333,  334,  335,  336,  338,  339,  340,  341,  342,  343,
      344,  346,  347,  348,  350,  351,  352,  353,  354,  355,
      356,  357,  358,  360,  362,  364,  365,  366,  368,  370,
      372,  374,  376,  378,  379,  380,  381,  382,  383,  384,
      386,  387,  388,  390,  391,  392,  394,  395,  397,  399,
      401,  403,  405,  406,  408,  408

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    8,   30,   31,   30,   30,   32,   33,
       34,   34,   34,   34,   34,   35,   34,   34,   34,   36,
       34,   34,   34,   34,   34,   34,   34,   37,   34,   34,
       38,   39,   40,   41,   42,    8,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   34,   52,   53,   54,   55,
       56,   57,   34,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    4,    1,    5,
        5,    5,    6,    1,    1,    1,    1,    1,    3,    6,
        6,    6,    6,    7,    8,    8,    9,    1,    3,    1,
        1,    7,    5,    5,    6,    6,    5,    5,    7,    7,
        7,    7,    8,    7,    9,    7,    8,    9,    7,    9,
        7,    9,    7,    9,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[309] =
    {   0,
        0,    0,   70,   73,   76,   82,  523,  524,   87,   90,
      495,  524,   76,  494,   76,  524,  524,  524,  493,   80,
      524,   83,   96,  492,  104,  151,  524,  524,   75,  491,
       77,  524,    0,  524,  524,  490,   87,  455,  457,   90,
       73,   89,   94,  458,   58,  457,  465,  104,  446,  455,
      453,  458,  524,   60,  524,  524,  524,  524,  496,  138,
      524,  524,  141,  177,  524,  172,  197,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  488,  189,  524,  193,
      167,  186,  145,  212,  524,  487,    0,  477,  524,  524,
      524,  476,    0,  524,  446,  445,  446,  439,  451,  438,

      453,  440,  446,  432,  433,  430,  430,  433,  430,  427,
        0,   70,  431,  189,  429,  181,  127,  433,  426,  172,
       92,  431,  524,  524,  524,  470,  469,  223,    0,  524,
      230,  233,    0,  252,    0,  524,  239,  176,  243,  247,
        0,  255,  524,  524,  423,  424,  434,  420,  432,  427,
      415,  216,  429,  427,  423,  415,  421,  424,    0,  410,
      414,    0,  415,  412,  402,  400,  402,  404,  411,  397,
      395,  395,  407,  397,  401,  405,  407,  396,  524,  257,
        0,  263,    0,  442,  253,  258,  524,  281,  394,  389,
      396,    0,  392,    0,    0,  383,  391,  380,  387,    0,

        0,  381,  378,    0,  382,    0,  377,  377,  376,  373,
      385,  375,  379,  384,  383,  381,  371,  375,    0,  348,
      351,  386,  385,  524,  524,  301,  278,  296,  305,    0,
      341,  340,    0,    0,  335,  336,  340,  302,    0,  309,
      295,  303,  297,    0,  305,  302,  299,  282,  291,  292,
        0,  282,  285,    0,  524,  524,  326,  339,  287,  278,
      268,  260,    0,    0,    0,  262,  254,    0,    0,    0,
        0,    0,    0,  249,  234,  204,  175,  157,  144,    0,
      124,  117,    0,  110,   87,    0,   50,    0,    0,    0,
        0,    0,   16,    0,  524,  362,  371,  376,  383,  390,

      396,  398,  400,  406,  411,  413,  415,  417
    } ;

static const flex_int16_t yy_def[309] =
    {   0,
      295,    1,  296,  296,  297,  297,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  298,  295,  295,  295,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  295,  295,  295,  295,  295,  295,  295,  299,
      295,  295,  300,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
       26,   81,  295,  295,  295,  301,   26,  295,  295,  295,
      295,  295,  298,  295,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  295,  295,  295,  295,  295,  295,  302,  295,
      295,  295,  303,  295,  304,  295,  295,  295,  295,  295,
      305,  301,  295,  295,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  295,  295,
      306,  295,  307,  304,  305,  308,  295,  295,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  295,  295,  295,  295,  304,  308,  295,  295,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  295,  295,  304,  304,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,    0,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295
    } ;

static const flex_int16_t yy_nxt[595] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,    8,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   26,   26,   27,   28,   29,   30,   31,   32,   33,
       33,   33,   33,   33,   33,   33,   33,   34,    8,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   33,
       45,   33,   46,   33,   33,   33,   33,   47,   48,   49,
       50,   51,   52,   33,   33,   33,   53,   54,   55,   56,
       57,   57,   58,   57,   57,   58,   58,   58,   58,   66,
      294,   62,   58,   58,   58,   69,  123,   62,   64,   64,
       64,   64,   64,   64,   72,   67,   67,   67,   67,   74,

       88,   89,   70,   91,   92,  111,   73,  293,   60,   75,
       76,   60,  112,   77,   63,   78,   78,   78,   78,  103,
       63,   80,  161,   81,   81,   81,   82,  124,  104,  162,
       95,   96,  100,  292,   83,   84,   85,   97,   85,  101,
       86,  105,  176,  106,  177,  102,  108,   83,  127,  109,
       84,   85,  107,  115,  116,  291,   85,  128,  128,  128,
      131,  132,  132,  117,  138,  138,  118,   86,   80,  170,
       87,   87,   87,   87,  129,   66,  290,  133,   64,   64,
       64,  289,   84,   85,  171,   85,   81,   81,   81,   82,
      288,   67,   67,   67,   67,  138,  138,   84,   85,  287,

      134,  129,  135,   85,  133,   82,   82,   82,   78,   78,
       78,   78,  137,  137,  137,  137,   67,   67,   67,   67,
       84,   85,  174,   85,   84,   85,  139,   85,  139,  168,
      175,  140,  140,  140,  140,   84,   85,  164,  286,   84,
       85,   85,  180,  180,  180,   85,  169,  165,  166,  182,
      182,  182,  182,  182,  182,  134,  285,  135,  137,  137,
      137,  137,  140,  140,  140,  140,  140,  140,  140,  140,
       84,   85,  186,   85,  196,  197,  222,  222,  222,   85,
      284,   85,  224,  224,  224,   84,   85,  187,  188,  187,
      188,   85,  187,  188,   85,  228,  283,  228,  282,   85,

      229,  229,  229,  229,  257,  187,  226,  187,  281,  188,
      187,  188,  187,  188,  188,  229,  229,  229,  229,  280,
      258,  258,  258,  258,  229,  229,  229,  229,  279,  257,
      187,  226,  278,  277,  188,  276,  275,  187,  274,  187,
      273,  272,  258,  271,  226,  258,  258,  258,  258,  270,
      269,  268,  187,  267,  266,  265,  264,  187,  258,  258,
      258,  258,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       93,   93,   93,   93,   93,  126,  263,  126,  262,  261,
      260,  126,  130,  259,  130,  256,  255,  254,  130,  142,

      142,  142,  181,  181,  183,  183,  184,  253,  184,  184,
      184,  184,  184,  184,  184,  185,  185,  223,  223,  225,
      225,  227,  227,  252,  227,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  226,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  195,  194,  193,  192,  191,  190,  189,  179,
      179,  178,  173,  172,  167,  163,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,

      146,  145,  144,  143,  141,  136,  125,  122,  121,  120,
      119,  114,  113,  110,   99,   98,   94,   90,   79,   71,
       68,   65,  295,    7,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295

    } ;

static const flex_int16_t yy_chk[595] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    4,    4,    4,    5,    5,    5,   13,
      293,    5,    6,    6,    6,   15,   54,    6,    9,    9,
        9,   10,   10,   10,   20,   13,   13,   13,   13,   22,

       29,   29,   15,   31,   31,   45,   20,  287,    3,   22,
       22,    4,   45,   23,    5,   23,   23,   23,   23,   41,
        6,   25,  112,   25,   25,   25,   25,   54,   41,  112,
       37,   37,   40,  285,   25,   25,   25,   37,   25,   40,
       25,   42,  121,   42,  121,   40,   43,   25,   60,   43,
       25,   25,   42,   48,   48,  284,   25,   60,   60,   60,
       63,   63,   63,   48,   83,   83,   48,   25,   26,  117,
       26,   26,   26,   26,   60,   66,  282,   63,   64,   64,
       64,  281,   26,   26,  117,   26,   81,   81,   81,   81,
      279,   66,   66,   66,   66,  138,  138,   26,   26,  278,

       67,   60,   67,   26,   63,   82,   82,   82,   78,   78,
       78,   78,   80,   80,   80,   80,   67,   67,   67,   67,
       78,   78,  120,   78,   80,   80,   84,   80,   84,  116,
      120,   84,   84,   84,   84,   78,   78,  114,  277,   80,
       80,   78,  128,  128,  128,   80,  116,  114,  114,  131,
      131,  131,  132,  132,  132,  134,  276,  134,  137,  137,
      137,  137,  139,  139,  139,  139,  140,  140,  140,  140,
      137,  137,  142,  137,  152,  152,  180,  180,  180,  140,
      275,  140,  182,  182,  182,  137,  137,  185,  185,  142,
      142,  137,  186,  186,  140,  188,  274,  188,  267,  140,

      188,  188,  188,  188,  226,  185,  226,  142,  266,  185,
      186,  142,  227,  227,  186,  228,  228,  228,  228,  262,
      226,  226,  226,  226,  229,  229,  229,  229,  261,  257,
      227,  257,  260,  259,  227,  253,  252,  229,  250,  229,
      249,  248,  258,  247,  258,  257,  257,  257,  257,  246,
      245,  243,  229,  242,  241,  240,  238,  229,  258,  258,
      258,  258,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      298,  298,  298,  298,  298,  299,  237,  299,  236,  235,
      232,  299,  300,  231,  300,  223,  222,  221,  300,  301,

      301,  301,  302,  302,  303,  303,  304,  220,  304,  304,
      304,  304,  304,  304,  304,  305,  305,  306,  306,  307,
      307,  308,  308,  218,  308,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  205,  203,  202,  199,
      198,  197,  196,  193,  191,  190,  189,  184,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  161,  160,  158,  157,  156,  155,
      154,  153,  151,  150,  149,  148,  147,  146,  145,  127,
      126,  122,  119,  118,  115,  113,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,

       96,   95,   92,   88,   86,   77,   59,   52,   51,   50,
       49,   47,   46,   44,   39,   38,   36,   30,   24,   19,
       14,   11,    7,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295

    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <stdio.h>
// #include "tokens.h"
#include "../Parser/parser.tab.h"

/* extern */ int line_number = 1;
/* extern */ char *filename;

#define DEFAULT_D_STR_LEN 32 /* >= 2 */

// YYSTYPE yylval;

#line 740 "lex.yy.c"

#line 742 "lex.yy.c"

#define INITIAL 0
#define char_lit 1
#define str_lit 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 18 "lexer.l"


#line 970 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 296 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 524 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];

find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 20 "lexer.l"
{return ';';}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "lexer.l"
{return '+';}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "lexer.l"
{return '-';}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "lexer.l"
{return '=';}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "lexer.l"
{return '-';}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "lexer.l"
{return '&';}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "lexer.l"
{return '|';}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 27 "lexer.l"
{return '(';}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 28 "lexer.l"
{return ')';}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "lexer.l"
{return '[';}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "lexer.l"
{return ']';}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "lexer.l"
{return '/';}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "lexer.l"
{return '%';}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "lexer.l"
{return '^';}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "lexer.l"
{return '!';}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "lexer.l"
{return '~';}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "lexer.l"
{return '.';}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "lexer.l"
{return '>';}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "lexer.l"
{return '<';}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "lexer.l"
{return ',';}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "lexer.l"
{return '.';}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "lexer.l"
{return ':';}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "lexer.l"
{return '?';}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "lexer.l"
{return '*';}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "lexer.l"
{return '{';}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "lexer.l"
{return '}';}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "lexer.l"
{return INDSEL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "lexer.l"
{return PLUSPLUS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "lexer.l"
{return MINUSMINUS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "lexer.l"
{return SHL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "lexer.l"
{return SHR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "lexer.l"
{return LEQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "lexer.l"
{return GEQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "lexer.l"
{return EQEQ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "lexer.l"
{return NEQ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "lexer.l"
{return LOGAND;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "lexer.l"
{return LOGOR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "lexer.l"
{return ELLIPSIS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "lexer.l"
{return TIMESEQ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "lexer.l"
{return DIVEQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "lexer.l"
{return MODEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "lexer.l"
{return PLUSEQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "lexer.l"
{return MINUSEQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "lexer.l"
{return SHLEQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "lexer.l"
{return SHREQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "lexer.l"
{return ANDEQ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "lexer.l"
{return OREQ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "lexer.l"
{return XOREQ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "lexer.l"
{return AUTO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "lexer.l"
{return BREAK;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "lexer.l"
{return CASE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "lexer.l"
{return CHAR;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "lexer.l"
{return CONST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "lexer.l"
{return CONTINUE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "lexer.l"
{return DEFAULT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "lexer.l"
{return DO;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "lexer.l"
{return DOUBLE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "lexer.l"
{return ELSE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "lexer.l"
{return ENUM;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "lexer.l"
{return EXTERN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "lexer.l"
{return FLOAT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "lexer.l"
{return FOR;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "lexer.l"
{return GOTO;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "lexer.l"
{return IF;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "lexer.l"
{return INLINE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "lexer.l"
{return INT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "lexer.l"
{return LONG;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "lexer.l"
{return REGISTER;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "lexer.l"
{return RESTRICT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "lexer.l"
{return RETURN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "lexer.l"
{return SHORT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "lexer.l"
{return SIGNED;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "lexer.l"
{return SIZEOF;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "lexer.l"
{return STATIC;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "lexer.l"
{return STRUCT;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 97 "lexer.l"
{return SWITCH;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 98 "lexer.l"
{return TYPEDEF;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 99 "lexer.l"
{return UNION;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 100 "lexer.l"
{return UNSIGNED;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 101 "lexer.l"
{return VOID;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 102 "lexer.l"
{return VOLATILE;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 103 "lexer.l"
{return WHILE;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 105 "lexer.l"
{return _BOOL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "lexer.l"
{return _COMPLEX;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "lexer.l"
{return _IMAGINARY;}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 109 "lexer.l"
{
    line_number++;
} /* catch newline and add line to line number */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 113 "lexer.l"
{ /* match preprocesser lines '# 41 main.c 1' and catch new filename and new line number */
    char extracted_filename[256];
    if (sscanf(yytext, "# %d \"%255[^\"]\"", &line_number, extracted_filename) >= 2) {
        filename = strdup(extracted_filename);
    }
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 120 "lexer.l"
{ /* decimal numbers */
    yylval.int_val = strtoll(yytext, NULL, 10);
    return NUMLIT;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 125 "lexer.l"
{ /* binary numbers */
    yylval.int_val = (long long int) strtoll(yytext+2, NULL, 2);
    return NUMLIT;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "lexer.l"
{ /* hex numbers */
    yylval.int_val = (long long int) strtoll(yytext+2, NULL, 16);
    return NUMLIT;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 135 "lexer.l"
{ /* octal numbers */
    yylval.int_val = (long long int) strtoll(yytext+1, NULL, 8);
    return NUMLIT;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 140 "lexer.l"
{ /* decimal floats and exponents */
    /* https://stackoverflow.com/a/12643073 */
    yylval.real_val = (long double) strtold(yytext, NULL);
    return FLOATLIT;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "lexer.l"
{ /* hex floats and exponents */
    /* https://stackoverflow.com/a/12643073 */
    yylval.real_val = (long double) strtold(yytext, NULL);
    return FLOATLIT;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 152 "lexer.l"
{BEGIN(char_lit);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 154 "lexer.l"
{
    switch (yytext[1]) {
        case 'a':
            yylval.char_val = '\a';
            break;
        case 'b':
            yylval.char_val = '\b';
            break;
        case 'e':
            yylval.char_val = '\033' /* \e */;
            break;
        case 'f':
            yylval.char_val = '\f';
            break;
        case 'n':
            yylval.char_val = '\n';
            break;
        case 'r':
            yylval.char_val = '\r';
            break;
        case 't':
            yylval.char_val = '\t';
            break;
        case 'v':
            yylval.char_val = '\v';
            break;
        case '\\':
            yylval.char_val = '\\';
            break;
        case '\'':
            yylval.char_val = '\'';
            break;
        case '\"':
            yylval.char_val = '\"';
            break;
        case '\?':
            yylval.char_val = '\?';
            break;
        default:
            REJECT
            break;
    }
    BEGIN(INITIAL);
    return CHARLIT;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 200 "lexer.l"
{
    char *endptr = yytext + 4;
    yylval.char_val = (char) strtoll(yytext + 2, &endptr, 16);
    BEGIN(INITIAL);
    return CHARLIT;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 207 "lexer.l"
{
    char *endptr = yytext + 4;
    yylval.char_val = (char) strtoll(yytext + 1, &endptr + 4, 8);
    BEGIN(INITIAL);
    return CHARLIT;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 214 "lexer.l"
{
    yylval.char_val = yytext[0];
    BEGIN(INITIAL);
    return CHARLIT;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 220 "lexer.l"
{
    REJECT
    BEGIN(INITIAL);
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 225 "lexer.l"
{
    yylval.d_str_val.str_val = (char*) calloc(DEFAULT_D_STR_LEN, sizeof(char));
    yylval.d_str_val.str_len = 0;
    yylval.d_str_val.str_max_len = DEFAULT_D_STR_LEN;
    BEGIN(str_lit);
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 232 "lexer.l"
{
    /* TODO */;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 236 "lexer.l"
{
    /* TODO */;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 240 "lexer.l"
{
    if (yylval.d_str_val.str_len + 2 > yylval.d_str_val.str_max_len) {
        yylval.d_str_val.str_val = realloc(yylval.d_str_val.str_val, yylval.d_str_val.str_max_len * 2);
        if (yylval.d_str_val.str_val == NULL) {
            REJECT
        }
        yylval.d_str_val.str_max_len *= 2;
    }
    switch (yytext[1]) {
    case 'a':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\a';
        break;
    case 'b':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\b';
        break;
    case 'e':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\033' /* \e */;
        break;
    case 'f':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\f';
        break;
    case 'n':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\n';
        break;
    case 'r':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\r';
        break;
    case 't':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\t';
        break;
    case 'v':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\v';
        break;
    case '\\':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\\';
        break;
    case '\'':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\'';
        break;
    case '\"':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\"';
        break;
    case '\?':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\?';
        break;
    case '0':
        yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\0';
        break;
    default:
        REJECT
        break;
    }
    yylval.d_str_val.str_len += 1;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 295 "lexer.l"
{ /* match any printable character other than backslash and double quote */
    if (yylval.d_str_val.str_len + 2 > yylval.d_str_val.str_max_len) {
        yylval.d_str_val.str_val = realloc(yylval.d_str_val.str_val, yylval.d_str_val.str_max_len * 2);
        if (yylval.d_str_val.str_val == NULL) {
            REJECT
        }
        yylval.d_str_val.str_max_len *= 2;
    }
    yylval.d_str_val.str_val[yylval.d_str_val.str_len] = yytext[0];
    yylval.d_str_val.str_len += 1;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 307 "lexer.l"
{
    yylval.d_str_val.str_val = realloc(yylval.d_str_val.str_val, yylval.d_str_val.str_len + 1);
    yylval.d_str_val.str_val[yylval.d_str_val.str_len] = '\0';
    yylval.d_str_val.str_len += 1;
    BEGIN(INITIAL);
    return STRLIT;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 315 "lexer.l"
{
    yylval.str_val = strdup(yytext);
    return IDENT;
}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 320 "lexer.l"
{}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 322 "lexer.l"
{printf("INVALID TOKEN: %s\n", yytext);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 324 "lexer.l"
ECHO;
	YY_BREAK
#line 1748 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(char_lit):
			case YY_STATE_EOF(str_lit):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 296 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 296 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 295);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 324 "lexer.l"


/* int main(int argc, char *argv[]) {
    int tok_id = yylex();

    do {
        if (tok_id == NUMLIT) {
			printf("TOKID: %d, LINE_NUM: %d, NUMLIT: %lld, TOKEN: %s\n", tok_id, line_number, yylval.int_val, yytext);
		} else if (tok_id == FLOATLIT) {
			printf("TOKID: %d, LINE_NUM: %d, FLIT: %Lf, TOKEN: %s\n", tok_id, line_number, yylval.real_val, yytext);
		} else if (tok_id == CHARLIT) {
            printf("TOKID: %d, LINE_NUM: %d, CHAR: \'%c\'\n", tok_id, line_number, yylval.char_val);
        } else if (tok_id == STRLIT) {
            printf("TOKID: %d, LINE_NUM: %d, STRLIT: \"%s\"\n", tok_id, line_number, yylval.str_val);
        } else {
			printf("TOKID: %d, LINE_NUM: %d, TOKEN: %s\n", tok_id, line_number, yytext);
		}
    } while (tok_id = yylex());
    
    return 0;
} */

int yywrap(){return(1);}
